"use strict";
const CONFIG_KEY="fitness-ai-supabase-config";
let db=null,user=null,profile=null,records={meals:[],activities:[],body:[],sleep:[],water:[]};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const show=id=>{["setupScreen","authScreen","app"].forEach(x=>$("#"+x).classList.toggle("hidden",x!==id))};
const toast=(m,bad=false)=>{const t=$("#toast");t.textContent=m;t.style.background=bad?"#ff7a86":"#5de8b6";t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2600)};
const esc=v=>{const d=document.createElement("div");d.textContent=String(v??"");return d.innerHTML};
const config=()=>{try{return JSON.parse(localStorage.getItem(CONFIG_KEY)||"null")}catch{return null}};
const localDate=(d=new Date())=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);
const day=v=>{const d=new Date(v);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
const today=v=>day(v)===day(new Date()); const sum=(a,k)=>a.reduce((n,x)=>n+(Number(x[k])||0),0); const percent=(a,b)=>Math.min(100,Math.max(0,a/b*100||0));
function client(c){db=window.supabase.createClient(c.url,c.key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}})}
async function boot(){const c=config();if(!c){show("setupScreen");return}try{client(c);const {data:{session}}=await db.auth.getSession();if(session){user=session.user;await enterApp()}else show("authScreen");db.auth.onAuthStateChange((event,session)=>{if(event==="SIGNED_OUT")show("authScreen");if(event==="PASSWORD_RECOVERY")toast("Open account recovery in Supabase to set a new password.")})}catch(e){show("setupScreen");toast("Connection could not be initialized",true)}}
$("#setupForm").addEventListener("submit",async e=>{e.preventDefault();const url=$("#setupUrl").value.trim().replace(/\/$/,""),key=$("#setupKey").value.trim();if(!/^https:\/\/[a-z0-9-]+\.supabase\.co$/i.test(url)){toast("Enter a valid Supabase project URL",true);return}localStorage.setItem(CONFIG_KEY,JSON.stringify({url,key}));location.reload()});
$("#changeConnection").onclick=()=>{if(confirm("Change the Supabase project used on this device?")){localStorage.removeItem(CONFIG_KEY);location.reload()}};
$$('[data-auth-tab]').forEach(b=>b.onclick=()=>{$$('[data-auth-tab]').forEach(x=>x.classList.toggle("active",x===b));$("#loginForm").classList.toggle("active",b.dataset.authTab==="login");$("#signupForm").classList.toggle("active",b.dataset.authTab==="signup")});
$("#signupTimezone").value=Intl.DateTimeFormat().resolvedOptions().timeZone;
$("#loginForm").addEventListener("submit",async e=>{e.preventDefault();busy(e.submitter,true);const f=new FormData(e.currentTarget),{data,error}=await db.auth.signInWithPassword({email:f.get("email").trim(),password:f.get("password")});busy(e.submitter,false);if(error)return toast(error.message,true);user=data.user;await enterApp()});
$("#signupForm").addEventListener("submit",async e=>{e.preventDefault();const b=e.submitter,f=new FormData(e.currentTarget);if(f.get("password")!==f.get("confirm_password"))return toast("Passwords do not match",true);busy(b,true);const detail={full_name:f.get("full_name").trim(),date_of_birth:f.get("date_of_birth"),sex_at_birth:f.get("sex_at_birth"),height_cm:+f.get("height_cm"),current_weight_kg:+f.get("current_weight_kg"),target_weight_kg:+f.get("target_weight_kg"),primary_goal:f.get("primary_goal"),activity_level:f.get("activity_level"),target_calories:+f.get("target_calories"),target_protein_g:+f.get("target_protein_g"),target_water_ml:+f.get("target_water_ml"),target_activity_minutes:+f.get("target_activity_minutes"),diet_preference:f.get("diet_preference"),allergies:f.get("allergies").trim(),health_notes:f.get("health_notes").trim(),timezone:f.get("timezone")};const {data,error}=await db.auth.signUp({email:f.get("email").trim(),password:f.get("password"),options:{data:detail,emailRedirectTo:location.href.split("#")[0]}});busy(b,false);if(error)return toast(error.message,true);if(data.session){user=data.user;await enterApp();toast("Account created")}else{toast("Account created. Check your email to confirm, then sign in.");document.querySelector('[data-auth-tab="login"]').click()}});
$("#forgotButton").onclick=async()=>{const email=prompt("Enter your account email:");if(!email)return;const {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:location.href.split("#")[0]});toast(error?error.message:"Password reset email sent",!!error)};
$("#logoutButton").onclick=async()=>{await db.auth.signOut();user=null;profile=null;show("authScreen")};
function busy(b,on){if(!b)return;b.disabled=on;b.dataset.label??=b.textContent;b.textContent=on?"Please wait…":b.dataset.label}
async function enterApp(){show("app");await Promise.all([loadProfile(),loadRecords()]);render()}
async function loadProfile(){const {data,error}=await db.from("profiles").select("*").eq("id",user.id).single();if(error)throw toast("Profile load failed: "+error.message,true);profile=data}
async function loadRecords(){const tables=[["meal_logs","meals"],["activity_logs","activities"],["body_logs","body"],["sleep_logs","sleep"],["water_logs","water"]];await Promise.all(tables.map(async([table,key])=>{const {data,error}=await db.from(table).select("*").order("logged_at",{ascending:false}).limit(100);if(error)throw new Error(error.message);records[key]=data||[]})).catch(e=>toast("Data load failed: "+e.message,true))}
function totals(){const m=records.meals.filter(x=>today(x.logged_at)),a=records.activities.filter(x=>today(x.logged_at)),s=records.sleep.filter(x=>today(x.logged_at)),w=records.water.filter(x=>today(x.logged_at));return{m,a,s,w,calories:sum(m,"calories"),protein:sum(m,"protein_g"),water:sum(w,"amount_ml"),activity:sum(a,"duration_minutes")}}
function score(t){return Math.round((Math.min(t.calories/profile.target_calories,1)*.15+Math.min(t.protein/profile.target_protein_g,1)*.25+Math.min(t.water/profile.target_water_ml,1)*.2+Math.min(t.activity/profile.target_activity_minutes,1)*.2+(t.s.length?Math.min(sum(t.s,"duration_hours")/7.5,1):0)*.2)*100)}
function render(){if(!profile)return;const t=totals();$("#dateLabel").textContent=new Intl.DateTimeFormat("en-MY",{weekday:"long",day:"numeric",month:"long"}).format(new Date());$("#greeting").textContent=`Hi, ${profile.full_name.split(" ")[0]}`;$("#goalText").textContent=`Goal: ${profile.primary_goal.replaceAll("_"," ")} • Target ${profile.target_weight_kg} kg`;$("#scoreValue").textContent=score(t);[["calories",t.calories,profile.target_calories,""],["protein",Math.round(t.protein),profile.target_protein_g," g"],["water",t.water,profile.target_water_ml," ml"],["activity",t.activity,profile.target_activity_minutes," min"]].forEach(([id,v,g,u])=>{$("#"+id+"Value").textContent=v+u;$("#"+id+"Target").textContent=`of ${g}${u}`;$("#"+id+"Bar").style.width=percent(v,g)+"%"});renderCoach(t);renderRows(t);fillProfile()}
function renderCoach(t){const s=score(t),ins=[];$("#coachOverview").textContent=s>=80?"You are meeting most of today’s wellbeing targets.":s>=50?"You have made good progress. Focus on the remaining gaps below.":"Build momentum with one meal log, water and a short activity.";if(t.protein<profile.target_protein_g*.7)ins.push(["warn",`${Math.max(0,Math.round(profile.target_protein_g-t.protein))} g protein remains today.`]);else ins.push(["",`Protein is on track at ${Math.round(t.protein)} g.`]);if(t.water<profile.target_water_ml*.7)ins.push(["warn",`${Math.max(0,profile.target_water_ml-t.water)} ml remains for hydration.`]);else ins.push(["","Hydration is on track."]);if(t.activity<profile.target_activity_minutes)ins.push(["warn",`${Math.max(0,profile.target_activity_minutes-t.activity)} active minutes remain.`]);else ins.push(["","Activity target achieved."]);$("#insights").innerHTML=ins.map(x=>`<div class="insight ${x[0]}">${x[1]}</div>`).join("")}
function rows(items,kind){if(!items.length)return '<div class="empty">No records today.</div>';return items.slice(0,5).map(x=>{let name=kind==="meal"?x.meal_name:x.activity_name,detail=kind==="meal"?`${x.calories} kcal • ${x.protein_g} g protein`:`${x.duration_minutes} min • ${x.source}`;return `<div class="row"><div><strong>${esc(name)}</strong><small>${new Date(x.logged_at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</small></div><span>${esc(detail)}</span></div>`}).join("")}
function renderRows(t){$("#mealList").innerHTML=rows(t.m,"meal");$("#activityList").innerHTML=rows(t.a,"activity");const all=[...records.meals.map(x=>({name:x.meal_name,detail:`${x.calories} kcal`,date:x.logged_at})),...records.activities.map(x=>({name:x.activity_name,detail:`${x.duration_minutes} min`,date:x.logged_at})),...records.body.map(x=>({name:`Weight ${x.weight_kg} kg`,detail:x.source,date:x.logged_at})),...records.sleep.map(x=>({name:`Sleep ${x.duration_hours} h`,detail:`Quality ${x.quality}/5`,date:x.logged_at})),...records.water.map(x=>({name:`Water ${x.amount_ml} ml`,detail:"Hydration",date:x.logged_at}))].sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,15);$("#recentList").innerHTML=all.map(x=>`<div class="row"><div><strong>${esc(x.name)}</strong><small>${new Date(x.date).toLocaleString()}</small></div><span>${esc(x.detail)}</span></div>`).join("")||'<div class="empty">Nothing logged yet.</div>'}
function fillProfile(){const f=$("#profileForm");["full_name","date_of_birth","sex_at_birth","height_cm","target_weight_kg","primary_goal","activity_level","diet_preference","target_calories","target_protein_g","target_water_ml","target_activity_minutes","allergies","health_notes"].forEach(k=>{if(f.elements[k])f.elements[k].value=profile[k]??""})}
$$('[data-view]').forEach(b=>b.onclick=()=>{$$('[data-view]').forEach(x=>x.classList.toggle("active",x===b));$$('.view').forEach(v=>v.classList.toggle("active",v.id===b.dataset.view));scrollTo(0,0)});$$('[data-open]').forEach(b=>b.onclick=()=>{const d=$("#"+b.dataset.open);d.querySelector('[name="logged_at"]').value=localDate();d.showModal()});$$('[data-close]').forEach(b=>b.onclick=()=>b.closest("dialog").close());$$('dialog').forEach(d=>d.onclick=e=>{if(e.target===d)d.close()});
function formObject(form){return Object.fromEntries(new FormData(form))}function num(o,keys){keys.forEach(k=>o[k]=o[k]===""?null:+o[k]);return o}
function addLog(formId,table,key,numbers){$(formId).addEventListener("submit",async e=>{e.preventDefault();const b=e.submitter;busy(b,true);let row=num(formObject(e.currentTarget),numbers);row.user_id=user.id;row.logged_at=new Date(row.logged_at).toISOString();const {data,error}=await db.from(table).insert(row).select().single();busy(b,false);if(error)return toast(error.message,true);records[key].unshift(data);e.currentTarget.reset();e.currentTarget.closest("dialog").close();render();toast("Saved successfully")})}
addLog("#mealForm","meal_logs","meals",["calories","protein_g","carbs_g","fat_g"]);addLog("#activityForm","activity_logs","activities",["duration_minutes","calories_burned","distance_km"]);addLog("#bodyForm","body_logs","body",["weight_kg","body_fat_percent","muscle_mass_kg","bmi"]);addLog("#sleepForm","sleep_logs","sleep",["duration_hours","quality"]);
$("#waterButton").onclick=async()=>{const {data,error}=await db.from("water_logs").insert({user_id:user.id,amount_ml:250,logged_at:new Date().toISOString()}).select().single();if(error)return toast(error.message,true);records.water.unshift(data);render();toast("250 ml water added")};
$("#refreshButton").onclick=async()=>{await loadRecords();render();toast("Data refreshed")};
$("#profileForm").addEventListener("submit",async e=>{e.preventDefault();let row=num(formObject(e.currentTarget),["height_cm","target_weight_kg","target_calories","target_protein_g","target_water_ml","target_activity_minutes"]);row.updated_at=new Date().toISOString();const {data,error}=await db.from("profiles").update(row).eq("id",user.id).select().single();if(error)return toast(error.message,true);profile=data;render();toast("Profile updated")});
$("#exportButton").onclick=()=>{const blob=new Blob([JSON.stringify({exported_at:new Date().toISOString(),profile,records},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`fitness-ai-export-${day(new Date())}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};
$("#deleteAccountData").onclick=async()=>{if(!confirm("Delete all meal, activity, body, sleep and water records? Your login and profile will remain."))return;const tables=["meal_logs","activity_logs","body_logs","sleep_logs","water_logs"];for(const table of tables){const {error}=await db.from(table).delete().eq("user_id",user.id);if(error)return toast(error.message,true)}await loadRecords();render();toast("Health records deleted")};
if("serviceWorker" in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./sw.js"));boot();